### ISSUE TITLE
Chromium version does not support passwords

### ISSUE THREAD

**Issue by stjet** [jetstream0/GoBanMe#6]

**Comment by HelloMokuzai** [comment]
Hi Prussia,

Adding to this - The chromium version requests the seed each time you try to use it. However once entered it works as intended.

**Comment by stjet** [comment]
Yup. This is because chrome store reviewers rejected many times, and I had to strip out a lot of the functionality, since I did not have the time to argue my case. Ho[efully in the future this will be fixed.

**Comment by stjet** [comment]
Will be fixed in next version probably
