### ISSUE TITLE
Update the chrome version

### ISSUE THREAD

**Issue by ninjamar** [jetstream0/GoBanMe#7]
Update the chrome version or at-least update the source code to manually install the extension.

**Comment by stjet** [comment]
Thanks for reminding me. Will do

**Comment by ninjamar** [comment]
:)

**Comment by stjet** [comment]
*Will do soon ™️ when not busy

**Comment by ninjamar** [comment]
> *Will do soon ™️ when not busy
ok

**Comment by stjet** [comment]
![image](https://user-images.githubusercontent.com/49297268/169200171-6e4faa6c-d9cb-4da2-a229-a0c130d4da46.png)
Soon :tm: whenever google decides to review my thing. Not super optimistic, the store is really annoying review wise. Usually have to appeal a couple times before it gets approved :( anyways yeah

**Comment by stjet** [comment]
I've added the new version in the chromium-parity version. You can now sideload it, so I will close this issue within a couple of days

**Comment by ninjamar** [comment]
> I've added the new version in the chromium-parity version. You can now sideload it, so I will close this issue within a couple of days

Thanks!
